package com.cash2qif.www;

public class Constants {
    static final String[] CATEGORIES = {
		"Bonus",
		"Div Income",
		"Employer Benefit",
		"Employer Benefit:Dental",
		"Employer Benefit:Medical",
		"Employer Benefit:Vision",
		"Gift Received",
		"Interest Inc",
		"Invest Inc",
		"Net Salary",
		"Other Inc",
		"Profit Sharing",
		"Salary",
		"Salary:Holiday",
		"Salary:Sick Pay",
		"Salary:Vacation",
		"Tax Refund",
		"Unemployment Inc",
		"Auto",
		"Auto:Fuel",
		"Auto:Insurance",
		"Auto:Loan",
		"Auto:Registration",
		"Auto:Service",
		"Bank Charge",
		"Cash",
		"Charity",
		"Charity-Non Cash",
		"Clothing",
		"Dining",
		"Education",
		"Entertainment",
		"Gifts Given",
		"Groceries",
		"Homeowner's Fees",
		"Household",
		"Insurance",
		"Insurance:Disability Insurance",
		"Insurance:Home Insurance",
		"Insurance:Life Insurance",
		"Interest Exp",
		"IRA Contrib",
		"Medical",
		"Medical:Doctor",
		"Medical:Medicine",
		"Misc",
		"Personal Care",
		"Recreation",
		"Rent",
		"Subscriptions",
		"Tax",
		"Tax:Fed",
		"Tax:Medicare",
		"Tax:Other",
		"Tax:SDI",
		"Tax:Soc Sec",
		"Tax:State",
		"Utilities",
		"Utilities:Cable TV",
		"Utilities:Garbage & Recycling",
		"Utilities:Gas & Electric",
		"Utilities:Internet",
		"Utilities:Telephone",
		"Utilities:Water",
		"Vacation",
		"Vacation:Lodging",
		"Vacation:Travel"};
}